# Generated by Django 3.2.9 on 2021-12-01 16:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_description', models.CharField(max_length=50, verbose_name='Local')),
                ('postal_code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='CEP')),
                ('street', models.CharField(max_length=50, verbose_name='Rua')),
                ('street_number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, default='', max_length=50, verbose_name='Complemento')),
                ('district', models.CharField(max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
