# Generated by Django 3.2.9 on 2021-12-01 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand_api', '0003_partsdemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='CEP'),
        ),
    ]
