# Generated by Django 3.2.9 on 2021-12-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand_api', '0004_alter_deliveryaddress_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'endereço de entrega', 'verbose_name_plural': 'endereços de entrega'},
        ),
    ]
