# Generated by Django 3.2.9 on 2021-12-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand_api', '0005_alter_deliveryaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsdemand',
            options={'verbose_name': 'demanda de peça', 'verbose_name_plural': 'demandas de peça'},
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='partsdemand',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_demand_api.deliveryaddress', verbose_name='Endereço de entrega'),
        ),
        migrations.AlterField(
            model_name='partsdemand',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status de finalização'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Usuário'),
        ),
    ]
